# Generated by Django 3.2.11 on 2022-03-19 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asrusagereport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromdate', models.DateTimeField(verbose_name='From Date')),
                ('todate', models.DateTimeField(verbose_name='To Date')),
                ('typeofreport', models.CharField(choices=[('Summary', 'Summary'), (' Detail', ' Detail')], default='Select', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Changepassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldpassword', models.CharField(max_length=100, verbose_name='Old Password')),
                ('newpassword', models.CharField(max_length=100, verbose_name='New Password')),
                ('retypepassword', models.CharField(max_length=100, verbose_name='Retype Password')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('mobile_no', models.CharField(max_length=12, verbose_name='Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(choices=[('Operator', 'Operator'), ('Supervisor', 'Supervisor'), (' Mechanical', ' Mechanical'), (' Electrical', ' Electrical'), (' Production', ' Production'), (' Management', ' Management')], default='Select', max_length=30)),
                ('employee_code', models.CharField(max_length=100, verbose_name='User Code')),
                ('employee_name', models.CharField(max_length=100, verbose_name='User Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile_no', models.CharField(max_length=12, verbose_name='Mobile Number')),
                ('is_login', models.BooleanField(default=False)),
                ('ip_address', models.CharField(blank=True, max_length=100, verbose_name='Mobile Number')),
            ],
        ),
        migrations.CreateModel(
            name='Materialinward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn', models.CharField(max_length=100, verbose_name='GRN')),
                ('ordernumber', models.CharField(max_length=100, verbose_name='ORDERNO')),
                ('orderrefnumber', models.CharField(max_length=100, verbose_name='ORDERREFNO')),
                ('fabricname', models.CharField(max_length=100, verbose_name='FABRICNAME')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('fabrictype', models.CharField(max_length=100, verbose_name='FABRICTYPE')),
                ('dia', models.CharField(max_length=100, verbose_name='DIA')),
                ('gsm', models.CharField(max_length=100, verbose_name='GSM')),
                ('batchnumber', models.CharField(max_length=100, verbose_name='BATCHNO')),
                ('rollsnumber', models.CharField(max_length=100, verbose_name='ROLLSNO')),
                ('totalweight', models.CharField(max_length=100, verbose_name='TOTALWEIGHT')),
                ('supplier', models.CharField(max_length=100, verbose_name='SUPPLIER')),
                ('idofpallet', models.CharField(choices=[('6730', '6730'), (' 6434 ', ' 6434 '), ('6030 ', '6030 '), ('6750 ', '6750 '), ('6477', '6477')], default='Select', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Qstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_status_code', models.CharField(max_length=100, verbose_name='Q Status Code')),
                ('q_status_name', models.CharField(max_length=100, verbose_name='Q Status Name')),
            ],
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_shifts', models.CharField(choices=[('2', '2'), ('3', '3')], default='Select', max_length=30)),
                ('shift_1_hour', models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], default='Select', max_length=30)),
                ('shift_1_min', models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], default='Select', max_length=30)),
                ('shift_2_hour', models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], default='Select', max_length=30)),
                ('shift_2_min', models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], default='Select', max_length=30)),
                ('shift_3_hour', models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], default='Select', max_length=30)),
                ('shift_3_min', models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], default='Select', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Toleranceweight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_weight_tolerance_plus', models.CharField(max_length=100, verbose_name='Tolerance Weight+')),
                ('main_weight_tolerance_minus', models.CharField(max_length=100, verbose_name='Tolerance Weight-')),
            ],
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palletid', models.CharField(max_length=100, verbose_name='Pallet Id')),
                ('palletcolor', models.CharField(max_length=100, verbose_name='Pallet Color')),
                ('palletweight', models.CharField(max_length=100, verbose_name='Pallet Weight')),
                ('palletsuplier', models.CharField(max_length=100, verbose_name='Pallet Suplier')),
                ('Toleranceweight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.toleranceweight')),
            ],
        ),
        migrations.CreateModel(
            name='Materialreload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Materialinward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.materialinward')),
            ],
        ),
        migrations.CreateModel(
            name='Materialoutward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Materialinward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.materialinward')),
            ],
        ),
        migrations.CreateModel(
            name='Adjustmentreprocess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Materialinward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.materialinward')),
            ],
        ),
    ]
