# Generated by Django 3.2.11 on 2022-03-06 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asrusagereport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField(verbose_name='From Date')),
                ('to_date', models.DateTimeField(verbose_name='To Date')),
            ],
        ),
        migrations.CreateModel(
            name='Changepassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_password', models.CharField(max_length=100, verbose_name='Old Password')),
                ('new_password', models.CharField(max_length=100, verbose_name='New Password')),
                ('retype_password', models.CharField(max_length=100, verbose_name='Retype Password')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('company_address', models.CharField(max_length=100, verbose_name='Address')),
                ('company_mobile_number', models.CharField(max_length=12, verbose_name='Number')),
                ('company_email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=100, verbose_name='User Code')),
                ('user_name', models.CharField(max_length=100, verbose_name='User Name')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('user_mobile_number', models.CharField(max_length=12, verbose_name='Mobile Number')),
                ('user_is_login', models.BooleanField(default=False)),
                ('user_ip_address', models.CharField(blank=True, max_length=100, verbose_name='Mobile Number')),
            ],
        ),
        migrations.CreateModel(
            name='Materialinward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn', models.CharField(max_length=100, verbose_name='GRN')),
                ('order_number', models.CharField(max_length=100, verbose_name='ORDERNO')),
                ('order_ref_number', models.CharField(max_length=100, verbose_name='ORDERREFNO')),
                ('fabric_name', models.CharField(max_length=100, verbose_name='FABRICNAME')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('fabric_type', models.CharField(max_length=100, verbose_name='FABRICTYPE')),
                ('dia', models.CharField(max_length=100, verbose_name='DIA')),
                ('gsm', models.CharField(max_length=100, verbose_name='GSM')),
                ('batch_number', models.CharField(max_length=100, verbose_name='BATCHNO')),
                ('roll_snumber', models.CharField(max_length=100, verbose_name='ROLLSNO')),
                ('total_weight', models.CharField(max_length=100, verbose_name='TOTALWEIGHT')),
                ('supplier', models.CharField(max_length=100, verbose_name='SUPPLIER')),
            ],
        ),
        migrations.CreateModel(
            name='Qstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_status_code', models.CharField(max_length=100, verbose_name='Q Status Code')),
                ('q_status_name', models.CharField(max_length=100, verbose_name='Q Status Name')),
            ],
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Toleranceweight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus', models.CharField(max_length=100, verbose_name='Tolerance Weight+')),
                ('minus', models.CharField(max_length=100, verbose_name='Tolerance Weight-')),
            ],
        ),
        migrations.CreateModel(
            name='Pallettwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_id', models.CharField(max_length=100, verbose_name='Pallet Id')),
                ('pallet_color', models.CharField(max_length=100, verbose_name='Pallet Color')),
                ('pallet_weight', models.CharField(max_length=100, verbose_name='Pallet Weight')),
                ('pallet_suplier', models.CharField(max_length=100, verbose_name='Pallet Suplier')),
                ('Toleranceweight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.toleranceweight')),
            ],
        ),
        migrations.CreateModel(
            name='Materialreload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Materialinward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.materialinward')),
            ],
        ),
        migrations.CreateModel(
            name='Materialoutward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Materialinward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.materialinward')),
            ],
        ),
        migrations.CreateModel(
            name='Adjustmentreprocess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Materialinward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.materialinward')),
            ],
        ),
    ]
