# Generated by Django 3.2.11 on 2022-03-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asrusagereport',
            name='type_of_report',
            field=models.CharField(choices=[('Summary', 'Summary'), (' Detail', ' Detail')], default='Select', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.CharField(choices=[('Operator', 'Operator'), ('Supervisor', 'Supervisor'), (' Mechanical', ' Mechanical'), (' Electrical', ' Electrical'), (' Production', ' Production'), (' Management', ' Management')], default='Select', max_length=30),
        ),
        migrations.AddField(
            model_name='materialinward',
            name='id_of_pallet',
            field=models.CharField(choices=[('6730', '6730'), (' 6434 ', ' 6434 '), ('6030 ', '6030 '), ('6750 ', '6750 '), ('6477', '6477')], default='Select', max_length=30),
        ),
        migrations.AddField(
            model_name='materialoutward',
            name='id_of_pallet',
            field=models.CharField(choices=[('6002', '6002'), ('6003', ' 6003 '), ('6004 ', '6004 '), ('6005 ', '6005 '), ('6006', '6006')], default='Select', max_length=30),
        ),
        migrations.AddField(
            model_name='shifts',
            name='four_start_time',
            field=models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], default='Select', max_length=30),
        ),
        migrations.AddField(
            model_name='shifts',
            name='one_start_time',
            field=models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], default='Select', max_length=30),
        ),
        migrations.AddField(
            model_name='shifts',
            name='shift',
            field=models.CharField(choices=[('2', '2'), ('3', '3')], default='Select', max_length=30),
        ),
        migrations.AddField(
            model_name='shifts',
            name='three_start_time',
            field=models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], default='Select', max_length=30),
        ),
        migrations.AddField(
            model_name='shifts',
            name='two_start_time',
            field=models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], default='Select', max_length=30),
        ),
    ]
